# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Is4JHmjN9pMxQN8z--9-3yCEYn10vT23
"""

inp3 = input("Enter your first name : ")
inp4 =input("Enter your last name")
print(f"Hello {inp3} {inp4} Welcome to the python program")