# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1mC14lhLZ2RnAw3M7byMxzzc5iKTp_B
"""

try:
  inp1 =int(input("Enter the first number : "))
  inp2= int(input("Enter the second number : "))
  def additionOftwoNum(a,b):
    print(f"Addition: {a+b}")
  def DifferenceOftwoNum(a,b):
    print(f"Subtraction: {a-b}")
  def ProductOftwoNum(a,b):
    print(f"Multiplication: {a*b}")
  def DivisionOftwoNum(a,b):
    print(f"Division: {a/b}")

  additionOftwoNum(inp1,inp2)
  DifferenceOftwoNum(inp1,inp2)
  ProductOftwoNum(inp1,inp2)
  DivisionOftwoNum(inp1,inp2)
except:
  print("invalid input,please enter numbers only")